$(function(){$(".erw_i .tri_r").click(function(){$(this).parents(".erw_i").addClass("erw_on");});$(".erw_i .tri_rc ").click(function(){$(this).parents(".erw_i").removeClass("erw_on");});$(".erw_i .erweiImg").hover(function(){$(this).find(".erm_tips_div").show();},function(){$(this).find(".erm_tips_div").hide();});$(".login_r .check_l").click(function(){var check=$(this).children(".input_c"),ownCheck=$(this).children(".own_check");var flag=check.attr("checked");if(!flag){check.attr("checked","true");ownCheck.addClass("own_check_on");ownCheck.next().addClass("own_check_text");}
else{check.removeAttr("checked");ownCheck.removeClass("own_check_on");ownCheck.next().removeClass("own_check_text");}});$(".input_div").each(function(){$(this).click(function(){var inputbox=$(this),tips=$(this).find(".tips");if($(this).hasClass("no_text")){inputbox.find(".input_t").val("");inputbox.removeClass("no_text");}})
$(this).find(".input_t").blur(function(){if($(this).val()==""){$(this).parents(".input_div").addClass("no_text");}});})
function hideTips(textbox,tips){textbox.find("textarea").val("");textbox.find("textarea").html("");textbox.removeClass("text_box_no");}
$(".text_box").click(function(){var textbox=$(this),tips=$(this).find(".tips");if($(this).hasClass("text_box_no")){hideTips(textbox,tips);}});$(".text_box textarea").blur(function(){if($(this).val()==""){$(this).parents(".text_box").addClass("text_box_no");}});$(".cut_down").each(function(){cutDown($(this));});function cutDown(cutDiv){cutDiv.height("auto");cutDiv.height(cutDiv.height()-1);cutDiv.css("overflow","hidden")}
$(".gdb_top_con .num_w").each(function(){var reNum=Number($(this).html()).toString(),n=8,tmp,numI;if(reNum.length<n){var m=n-reNum.length,addS="";for(var i=0;i<m;i++){addS+="*";}
reNum=addS+reNum;}
$(this).html("");for(var i=0;i<reNum.length;i++){tmp=reNum.charAt(i);if(!(tmp=="*")){numI="<i class='GNum GNum_"+tmp+"'>"+tmp+"</i>";if((reNum.length-i-1)%3==0&&(i+1)<reNum.length){numI+="<i class='GDot' style=' float:left;'>,</i>";}
$(this).append(numI);}}});$('#li_city_box li').mouseover(function(){$('#li_city_box li').removeClass('cur')
$(this).addClass('cur');var cid=$(this).attr('item');$('.city_box').hide();$('#city_box'+cid).show();});$('#province_s').change(function(){var parent_id=$(this).val();if(parent_id){$.get(JYUrl("ajax","childnykjarea",{parent_id:parent_id}),function(data){$('#city_s').html('<option value="0">选择市</option>'+data);});}});$('#city_s').change(function(){var city_id=$(this).val();if(city_id){$.ajax({url:JYUrl("ajax","getUnitByCity"),type:'post',dataType:'json',data:{c:city_id},success:function(json){var html='<option value="0">选择医院</option>';for(var k in json){html+='<option value="'+json[k].unit_id+'">'+json[k].unit_name+'</option>'}
$('#unit_s').html(html);}});}});$('#unit_s').change(function(){var unit_id=$(this).val();if(unit_id){$.ajax({url:JYUrl("ajax","getDepByUnit"),type:'post',dataType:'json',data:{keyValue:unit_id},success:function(json){var html='<option value="0">选择科室</option>';for(var k in json){html+='<option value="'+json[k].val+'">'+json[k].text+'</option>'}
$('#dep_s').html(html);}});}});$('#quick_btn').click(function(){if($('#city_s').val()=='0'){alert('请选择城市');return false;}
var unit_id=$('#unit_s').val();if(unit_id=='0'){alert('请选择医院');return false;}
var dep_id=$('#dep_s').val();var url='';if(dep_id=='0'){url=JYUrl("unit","show",{uid:unit_id});}else{url=JYUrl("dep","show",{depid:dep_id});}
location.href=url;});var time_exist=false;$("#codeLogin_btn").click(function(){if(time_exist==false){if(!$("#scanimg").attr('src')){$.getJSON('/main/getscancode',function(o){$("#saltvl").val(o.saltvl);$("#curip").val(o.curip);$("#scanimg").attr('src','/main/outScancode/salt-'+o.saltvl);});}
timeIDs=setInterval('chlink(timeIDs)',3000);time_exist=true;}});$("#consult_dep li").click(function(){$("#consult_dep li").removeClass("cur");$(this).addClass("cur");cno=$(this).find('a').attr('data');doctorList('consult',cno);});$("#group_li li").click(function(){$("#group_li li").removeClass("cur");$(this).addClass("cur");cno=$(this).attr('item');forumList(cno);});$('#new_ch li').click(function(){$('#new_ch li').removeClass('cur');$(this).addClass('cur');var show_box=$(this).attr('item');if(show_box=='news_box'){$('#news_box').show();$('#health_box').hide();}else{$('#news_box').hide();$('#health_box').show();}});$('#disease_ul li').click(function(){$('#disease_ul li').removeClass('cur');$(this).addClass('cur');var show_box=$(this).attr('item');$('.disease_c').hide();$('#'+show_box).show();});doctorList('consult');forumList(5);});function forumList(cno){url=JYUrl('ajax','getForumByCategory'),$.post(url,{cid:cno,num:14},function(result){html='';$.each(result,function(i,doc){var url=JYUrl("forum","detail",{id:doc.forum_id});html+='<li><i class="dot">◆</i>';html+='<p class="word_hid"><a href="'+url+'" class="fs14" title="'+doc.title+'">'+doc.title+'</a></p>';html+='<span class="fr gray_2 word_hid " title="'+doc.user_name+'">';if(doc.sex){html+='<i class="g_icon female"></i>';}else{html+='<i class="g_icon male"></i>';}
html+=doc.user_name+'</span></li>';});$("#forum_list").html(html);},'json');}
function doctorList(type,cno){url=JYUrl('consult','ajaxGetDocList'),$.post(url,{type:type,cno:cno,num:4},function(result){html='';$.each(result,function(i,doc){html+='<li>';html+='<div class="layout mt20">';html+='<a href="'+doc.doc_url+'" class="fl c_doca">';if(doc.image){html+='<img oncontextmenu="return(false);" src= '+upload_url+doc.image+' alt="" width="90" height="100"/>';}else{html+='<img oncontextmenu="return(false);" src="'+v2_files_dir+'/style/global/m_'+doc.sex+'.jpg" alt="" width="90" height="100"/>';}
html+='</a>';html+='<div class="fl d_info">';html+='<p><a href="'+doc.doc_url+'" class="d_name">'+doc.doctor_name+'</a></p>';html+='<p class="fs12 gray_1">'+doc.zcname+'</p>';html+='<p class="fs12"><em>'+doc.review_score+'</em>分<span class="fr gray_1">'+doc.review_people+'人点评</span></p>';html+='</div>';html+='</div>';html+='<div class="mt20 d_hos">';html+='<p class=""><a href="'+doc.unit_url+'" class="hos_n word_hid">'+doc.unit_name+'</a><a href="'+doc.dep_url+'" class="gray_1 dep_n word_hid">'+doc.dep_name+'</a></p>';html+='<p class="fs12 gray_1 mt8 d_det">'+doc.expert+'</p>';html+='</div>';html+='<div class="doc_bottom"><span class="fl"><em class="fs24">'+doc.cost_price+'</em>元／次</span><a href="'+doc.ask_url+'"><span class="btn btn_con fr"><i class="g_icon msg_c ver_m"></i>咨询</span></a></div></li>';});$("#consult_list").html(html);},'json');}
function chlink(timeIDs){var salt=document.getElementById('saltvl').value;var curip=document.getElementById('curip').value
var url="/main/scanLogin/salt-"+salt+"/curip-"+curip;if(salt&&curip){$.getJSON(url,function(o){if(o.code==1){clearInterval(timeIDs);window.location=JYUserUrl('sso/scan','',{salt:salt,target:window.location.href},'user.91160.com');}else if(o.code==-3){clearInterval(timeIDs);}});}}